### ISSUE TITLE
Illegal characters in metric names

### ISSUE THREAD

**Issue by ghost** [opsdis/monitor-exporter#28]
Scraping of several targets failed because of illegal metric names. I have added some code to our perfdata.py to try and solve this
[diff.txt](https://github.com/opsdis/monitor-exporter/files/8814013/diff.txt)

**Comment by thenodon** [comment]
Thanks for your input. Could you please instead fork the repo and make a pull request.

**Comment by ghost** [comment]
Done. Don't know if I should leave the pull request open or close it.

**Comment by thenodon** [comment]
Fix in pull request #29
