### ISSUE TITLE
50 service limit per host

### ISSUE THREAD

**Issue by cicigee** [opsdis/monitor-exporter#4]
When used in a system with OP5 monitor, only the first 50 services of a particular host are available at the /metrics endpoint.

To reproduce: Add more than 50 services to a host in monitor, then access */metrics?target=somehostname* and compare the amount of unique *service* labels to the amount of services connected to that host in monitor.

OP5 monitor version: 7.3.17
monitor-exporter version: 0.0.2

**Comment by cicigee** [comment]
Issue appears to be caused by pagination in OP5 API. It limits results to 50 if *limit* is not specified.


Tested this with:
op5host=''
credentials=''

for anumber in {1..105};
do 
myvar='{"check_command": "check_ping", "check_interval": "5", "check_period": "24x7", "file_id": "etc/services.cfg", "host_name": "luke_atesthost", "max_check_attempts": "15", "notification_interval": "0", "notification_options": ["c","f","r","s","u","w"], "notification_period": "24x7", "retry_interval": "1", "service_description": "a_dummy_check_'$anumber'", "template": "default-service"}';
curl -H 'content-type: application/json' -d "$myvar" "https://$op5host/api/config/service" -u "$credentials";
done

Issue is also occurring with Monitor version 8.0.7.

**Comment by thenodon** [comment]
Solved in merge
